version: '3'


services:
  db:
    image: mysql:8.0
    restart: always
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: "Fusion_db"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./tmp/db:/var/pkg/mysql
    ports:
      - 9999:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8mb4_unicode_ci

  api:
    build: ./api

  telegram_bot:
    build: ./clients/telegram_bot

  habr_api:
    build: habr_ru_api

  api_data_collector:
    build: api_data_collector

  lenta_api:
    build: services_py/scrapers_py/lenta_ru

  komers_api:
    build: services_py/scrapers_py/kommersant_ru

  midjourney_api:
    build: services_py/scrapers_py/midjourney

  ua_news_api:
    build: services_py/scrapers_py/online_ua_news

  ria_api:
    build: services_py/scrapers_py/ria_ru

  vz_ru_api:
    build: services_py/scrapers_py/vz_ru
